### ISSUE TITLE
Move commands always result in an HTTP Error 500: INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by gkaldev** [balta2ar/brotab#119]
Whether moving tabs with the CLI move command, through the python API, or just with a curl, I'm always getting an HTTP 500 error with move commands (see below for full error message).

All other commands (list, close, update, activate, etc) work just fine.
I'm successfully connected to the mediators:
```
~  $ bt clients
a.      localhost:4625  260230  chrome/chromium
```

However move results in this error:
```
~  $ bt move
MOVE [(2071267041, 2071267039, 0)]
Traceback (most recent call last):
  File "/home/ANT.AMAZON.COM/rekal/.local/bin/bt", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ANT.AMAZON.COM/rekal/.local/share/pipx/venvs/brotab/lib/python3.12/site-packages/brotab/main.py", line 769, in main
    exit(run_commands(sys.argv[1:]))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ANT.AMAZON.COM/rekal/.local/share/pipx/venvs/brotab/lib/python3.12/site-packages/brotab/main.py", line 762, in run_commands
    result = args.func(args)
             ^^^^^^^^^^^^^^^
  File "/home/ANT.AMAZON.COM/rekal/.local/share/pipx/venvs/brotab/lib/python3.12/site-packages/brotab/main.py", line 135, in move_tabs
    api.move_tabs([])
  File "/home/ANT.AMAZON.COM/rekal/.local/share/pipx/venvs/brotab/lib/python3.12/site-packages/brotab/api.py", line 407, in move_tabs
    self._move_tabs_if_changed(
  File "/home/ANT.AMAZON.COM/rekal/.local/share/pipx/venvs/brotab/lib/python3.12/site-packages/brotab/api.py", line 370, in _move_tabs_if_changed
    api.move_tabs(move_commands)
  File "/home/ANT.AMAZON.COM/rekal/.local/share/pipx/venvs/brotab/lib/python3.12/site-packages/brotab/api.py", line 226, in move_tabs
    return self._get('/move_tabs/%s' % quote_plus(commands))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ANT.AMAZON.COM/rekal/.local/share/pipx/venvs/brotab/lib/python3.12/site-packages/brotab/api.py", line 295, in _get
    return self._client.get(path, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ANT.AMAZON.COM/rekal/.local/share/pipx/venvs/brotab/lib/python3.12/site-packages/brotab/api.py", line 48, in get
    with urlopen(request, timeout=self._timeout) as response:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: INTERNAL SERVER ERROR
```

**Comment by gkaldev** [comment]
Happy to dive into this and debug further if someone can provide some pointers on how to get started or where to look.
I enabled logging as per [instructions here](https://github.com/balta2ar/brotab/wiki/Logging-in-Chrome) but there wasn't anything else logged besides the error line itself.

Is the only way to investigate further to set up the development environment for brotab and build / load a dev extension to run locally?

**Comment by xunoaib** [comment]
It looks like the route parameter name (`query_info`) just needs to be updated to match what `move_tabs` expects (`move_triplets`).

Here's the relevant section from my error log (`/tmp/brotab_mediator.log`):

```
2025-10-03 23:25:00,998 874670 ERROR    app.py:1741:log_exception Exception on /move_tabs/41+55+13 [GET]
Traceback (most recent call last):
  File "/home/user/.local/share/pipx/venvs/brotab/lib/python3.13/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/.local/share/pipx/venvs/brotab/lib/python3.13/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/.local/share/pipx/venvs/brotab/lib/python3.13/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/.local/share/pipx/venvs/brotab/lib/python3.13/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
TypeError: MediatorHttpServer.move_tabs() got an unexpected keyword argument 'query_info'
```
