### ISSUE TITLE
Fedora 41, Python 3.13: No output

### ISSUE THREAD

**Issue by lamyergeier** [balta2ar/brotab#120]
# Note

I have installed the extension on Firefox and both are updated. It was working fine in the last month with the previous Fedora version.

# No output for `clients` and `list`

```
$ pipx install brotab
  installed package brotab 1.4.2, installed using Python 3.13.0
  These apps are now globally available
    - brotab
    - bt
    - bt_mediator
done! ✨ 🌟 ✨
```

```
$ brotab install
Installing mediator manifest /home/lamy/.mozilla/native-messaging-hosts/brotab_mediator.json
Installing mediator manifest /home/lamy/.config/chromium/NativeMessagingHosts/brotab_mediator.json
Installing mediator manifest /home/lamy/.config/google-chrome/NativeMessagingHosts/brotab_mediator.json
Installing mediator manifest /home/lamy/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts/brotab_mediator.json
Link to Firefox extension: https://addons.mozilla.org/en-US/firefox/addon/brotab/
Link to Chrome (Chromium)/Brave extension: https://chrome.google.com/webstore/detail/brotab/mhpeahbikehnfkfnmopaigggliclhmnc/
```

```
$ brotab clients
$ brotab list
```

# What I tried

- Installation from master branch (latest commit)

```bash
$ pipx install git+https://github.com/balta2ar/brotab.git
```

``` bash
Traceback (most recent call last):
  File "/home/lamy/.local/bin/pipx", line 8, in <module>
    sys.exit(cli())
             ~~~^^
  File "/usr/lib/python3.13/site-packages/pipx/main.py", line 1176, in cli
    return run_pipx_command(parsed_pipx_args, subparsers)
  File "/usr/lib/python3.13/site-packages/pipx/main.py", line 282, in run_pipx_command
    return commands.install(
           ~~~~~~~~~~~~~~~~^
        None,
        ^^^^^
    ...<13 lines>...
        python_flag_passed=python_flag_passed,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3.13/site-packages/pipx/commands/install.py", line 47, in install
    package_name_from_spec(package_spec, python, pip_args=pip_args, verbose=verbose)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pipx/commands/common.py", line 388, in package_name_from_spec
    package_name = venv.install_package_no_deps(package_or_url=package_spec, pip_args=pip_args)
  File "/usr/lib/python3.13/site-packages/pipx/venv.py", line 314, in install_package_no_deps
    old_package_set = self.list_installed_packages()
  File "/usr/lib/python3.13/site-packages/pipx/venv.py", line 398, in list_installed_packages
    pip_list = json.loads(cmd_run.stdout.strip())
  File "/usr/lib64/python3.13/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/lib64/python3.13/json/decoder.py", line 344, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/json/decoder.py", line 362, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by doctorcolossus** [comment]
I am confused about the traceback. You don't provide the command you ran to produce it, but it looks like it comes from `pipx`. However, at the beginning of the issue, you show successful output of using `pipx` to install `brotab`.

I also just upgraded to Python 3.13 and am having the same issue so far... Have you figured anything out?

Did you try checking the output of `bt_mediator`?

**Comment by doctorcolossus** [comment]
For me the problem turned out to still be https://github.com/balta2ar/brotab/issues/105, the `werkzeug` package incompatibility. This was because the PyPI package apparently hasn't been updated to include the fixed requirements, so I was able fix the issue by cloning from the github repository, `cd`ing into the repo, and running `pip install .` to install the latest.

**Comment by lamyergeier** [comment]
> I am confused about the traceback. You don't provide the command you ran to produce it, but it looks like it comes from `pipx`. However, at the beginning of the issue, you show successful output of using `pipx` to install `brotab`.
> 
> I also just upgraded to Python 3.13 and am having the same issue so far... Have you figured anything out?
> 
> Did you try checking the output of `bt_mediator`?

The command is mentioned, immediately before the traceback and yes it from pipx. This second command  installs using the latest git repository, while other installs the latest release version

**Comment by doctorcolossus** [comment]
So it is, my bad. Hmm, did you try installing via `pip`, rather than `pipx`? `pip` worked for me, though I didn't try `pipx`.

**Comment by doctorcolossus** [comment]
It looks like probably this issue:
- https://github.com/pypa/pipx/issues/393
- https://github.com/pypa/pipx/issues/841

The second one says: "Further debugging somehow shows that pip is not available in the venv."

**Comment by doctorcolossus** [comment]
Have you tried checking the output of `bt_mediator` to confirm whether your lack of output is caused by https://github.com/balta2ar/brotab/issues/105?

**Comment by lamyergeier** [comment]
`bt_mediator` has no output. I have installed the latest commit in the git repository using pipx. The latest commit has `Werkzeug<3.0`

**Comment by doctorcolossus** [comment]
Cool, no output is a good thing, as that should indicate that it's running and didn't error out.

Since you have upgraded `brotab` now, have you tried restarting your browser and/or enabling/disabling the browser extension, and then trying `bt clients` and `bt list` again?

If so, and it's still not working, then my next idea would be to check for errors in the browser console, like in issue https://github.com/balta2ar/brotab/issues/115.
