### ISSUE TITLE
Doesn't work on macOS (wrong manifest directory)

### ISSUE THREAD

**Issue by thepaul** [balta2ar/brotab#43]
Everything seems to install correctly, but the `bt` command-line tool can't find any clients to talk to (empty output from `bt clients` and `bt list`).

After some debugging I found that the tool is installing the native-messaging manifest in the wrong directory. `~/.mozilla/native-messaging-hosts` is the directory for Firefox on Linux. For Firefox on Mac, it should be in `~/Library/Application Support/Mozilla/NativeMessagingHosts`. Moving the manifest file into the correct directory and reloading the extension makes everything work. Yay!

I don't know the correct directories for native messaging manifests under Chrome or Brave, but it looks like they need similar changes to work on macOS.

**Comment by felciano** [comment]
I've got this issue as well. Is there a recommended solution for Mac across Firefox, Chrome and Safari?

**Comment by twisst** [comment]
@thepaul's solution to this problem worked for me as well. I only had to create that directory myself. Restarted Firefox and it worked!

**Comment by mskar** [comment]
I ran this code but still no luck with either Firefox or Chrome:
```
bt install 
mkdir -p ~/Library/Application| Support/BraveSoftware/Brave-Browser/NativeMessagingHosts
cp -i ~/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts/brotab_mediator.json ~/Library/Application\ Support/BraveSoftware/Brave-Browser/NativeMessagingHosts
```
There is still no output from `bt list`...

**Comment by minamotorin** [comment]
Is your brotab‘s extension page‘s url is ` chrome-extension://mhpeahbikehnfkfnmopaigggliclhmnc/ ` ? If you installed brotab extension manually, you should add your brotab‘s extension page‘s url to ` brotab_mediator.json ` .

**Comment by jswent** [comment]
If anyone is still having an issue with Brave not working, putting the `brotab_mediator.json` file in the Chrome NativeMessagingHosts directory (`~/Library/Application Support/Google/Chrome/NativeMessagingHosts`) solved the issue for me.

**Comment by rickallauigan** [comment]
## This works on me:
Note: Replace `<HOME_FOLDER>` with your home folder

### Microsoft Edge:

1. Run `bt install`
![bt install](https://user-images.githubusercontent.com/10782187/194534272-a59ed143-b64d-4995-b309-ab5c20a9927f.png)

2. Create directory for `Microsoft Edge/NativeMessagingHosts` if not exists
    ```bash
    mkdir -p "/Users/<HOME_FOLDER>/Library/Application Support/Microsoft Edge/NativeMessagingHosts"
    ```
3. Copy `brotab_mediator.json` file from `chromium` to `Microsoft Edge/NativeMessagingHosts`
    ```bash
    cp /Users/<HOME_FOLDER>/.config/chromium/NativeMessagingHosts/brotab_mediator.json "/Users/<HOME_FOLDER>/Library/Application Support/Microsoft Edge/NativeMessagingHosts"
    ```
4. Re-install brotab chrome extension (this also works on Microsoft Edge):
    - url: https://chrome.google.com/webstore/detail/brotab/mhpeahbikehnfkfnmopaigggliclhmnc/
5. Run `bt clients`, results should be (if you also have firefox):
![image](https://user-images.githubusercontent.com/10782187/194533467-9ce5d27c-76de-4ba5-9562-e164c694434f.png)

### For Mozilla:

Brotab mediator location: `~/.mozilla/native-messaging-hosts/brotab_mediator.json`
Target directory: `/Users/<HOME_FOLDER>/Library/Application Support/Mozilla/NativeMessagingHosts`

### For Google Chrome: 
Brotab mediator location: `~/.config/google-chrome/NativeMessagingHosts/brotab_mediator.json`
Target directory: `/Users/<HOME_FOLDER>/Library/Application Support/Google/Chrome/NativeMessagingHosts`

**Comment by grandkrav** [comment]
I have the same issue on macOS with Firefox and Chrome - `bt clients` return nothing.
I have tried to change the mediator location - but it does not help. 

OS: macOS 13.4
Firefox: 121.0.1
Chrome: Version 120.0.6099.199 (Official Build) (arm64)

**Comment by grandkrav** [comment]
> I have the same issue on macOS with Firefox and Chrome - `bt clients` return nothing. I have tried to change the mediator location - but it does not help.
> 
> OS: macOS 13.4 Firefox: 121.0.1 Chrome: Version 120.0.6099.199 (Official Build) (arm64)

Found the root cause: `bt_mediator` return error:

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/bt_mediator", line 5, in <module>
    from brotab.mediator.brotab_mediator import main
  File "/opt/homebrew/lib/python3.11/site-packages/brotab/mediator/brotab_mediator.py", line 15, in <module>
    from brotab.mediator.http_server import MediatorHttpServer
  File "/opt/homebrew/lib/python3.11/site-packages/brotab/mediator/http_server.py", line 7, in <module>
    from flask import Flask
  File "/opt/homebrew/lib/python3.11/site-packages/flask/__init__.py", line 7, in <module>
    from .app import Flask as Flask
  File "/opt/homebrew/lib/python3.11/site-packages/flask/app.py", line 28, in <module>
    from . import cli
  File "/opt/homebrew/lib/python3.11/site-packages/flask/cli.py", line 18, in <module>
    from .helpers import get_debug_flag
  File "/opt/homebrew/lib/python3.11/site-packages/flask/helpers.py", line 16, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/opt/homebrew/lib/python3.11/site-packages/werkzeug/urls.py)
```

It looks like the Flask version is not compatible with the Werkzeug.

`pip uninstall werkzeug && pip install werkzeug==2`
