### ISSUE TITLE
Throwing this error:

### ISSUE THREAD

**Issue by rcrx** [balta2ar/brotab#59]
```
Traceback (most recent call last):
  File "/usr/local/bin/brotab", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/brotab/main.py", line 670, in main
    exit(run_commands(sys.argv[1:]))
  File "/usr/local/lib/python3.8/dist-packages/brotab/main.py", line 663, in run_commands
    result = args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/brotab/main.py", line 148, in list_tabs
    api = MultipleMediatorsAPI(create_clients(args.target_hosts))
  File "/usr/local/lib/python3.8/dist-packages/brotab/main.py", line 114, in create_clients
    hosts, ports = parse_target_hosts(target_hosts)
  File "/usr/local/lib/python3.8/dist-packages/brotab/main.py", line 103, in parse_target_hosts
    host, port = pair.split(':')
ValueError: not enough values to unpack (expected 2, got 1)
```
Not sure what to do with this. Explanation needed.

**Comment by balta2ar** [comment]
how are you running list tabs command? I assume you run it with this argument:
```
bt --target localhost:4626 list
```
are you missing port number? e.g. `--target localhost`

**Comment by rcrx** [comment]
Yes
