### ISSUE TITLE
print active tab

### ISSUE THREAD

**Issue by vredesbyyrd** [balta2ar/brotab#6]
Hi, 

I am working on a simple Rofi interface for brotab. I am trying to leverage rofi's `-selected-row` option so I can signify the _active_ tab on startup. Brotabs  `active` argument does not seem to be working though, or at least for me. Running `bt active` does not return any results. I am running a single instance of firefox, 

Firefox issue perhaps? If you have any thoughts on how to troubleshoot this I would love to hear them. Thanks for your time! 

**env info:**

Firefox 68.0.2-1
Arch Linux 5.2.8-1
Python 3.7.4-1

**Comment by balta2ar** [comment]
Hi! Do other commands work or produce any output, such as `bt list`, for example?

Brotab should be writing logs from client and mediator's point of view, take a look at these files:
* /tmp/brotab.log
* /tmp/brotab_mediator.log

Is anything logged when you execute `activate`?

How did you install Firefox extension? I'm not sure that the extension in the Mozilla Market is the latest... I'm afraid you might want to install the extension in dev mode from sources.

**Comment by vredesbyyrd** [comment]
Appreciate the response. 

The main arguments I use all work, which are: `bt list`, `activate`, `close`. I cloned this repo and used mozilla's `web-ext run` tool to make sure I was running the latest code, but the results were the same. 

> Is anything logged when you execute `activate`?

Just to make sure we are on the same page, `activate` works fine. I am interested in `active` ...

> display active tab for each client/window in the following format: "<prefix>.<window_id>.<tab_id>"

When running `bt active`,  and tailing the _brotab.log_ I see:

```
2019-08-15 14:00:36,812 INFO       Logger has been created
2019-08-15 14:00:36,819 INFO       Showing active tabs: Namespace(func=<function show_active_tab at 0x7f8981a3ba70>)
2019-08-15 14:00:36,819 INFO       Created clients: []

```
  _brotab_mediator.log_ does not print anything new.  Its not that big of a deal if I cannot get it to work. Just figured it would be a nice touch for "rofi-brotab" to highlight the active tab. This is what I have so far. Its limited to only _activating_ and _closing_ tabs. But you can select multiple tabs to close in one shot which is nice. 

![rofi-2019-08-15-1159-00000](https://user-images.githubusercontent.com/22080838/63119626-38ade280-bf66-11e9-9283-c31a16c99ab5.png)

**Comment by pkfm** [comment]
Here are what the logs produce for the `activate` command on my initial install:

```
# /tmp/brotab.log
2019-12-03 14:20:14,331 INFO       Logger has been created
2019-12-03 14:20:14,342 INFO       Showing active tabs: Namespace(func=<function show_active_tab at 0x7ff1714fcf80>)
2019-12-03 14:20:14,343 INFO       GET http://localhost:4625/get_pid
2019-12-03 14:20:14,350 INFO       GET http://localhost:4625/get_browser
2019-12-03 14:20:14,366 INFO       Created clients: [<brotab.main.FirefoxMediatorAPI object at 0x7ff171be37d0>]
```

```
# /tmp/brotab_mediator.log
2019-12-03 22:20:14,349 2637  INFO       127.0.0.1 - - [03/Dec/2019 22:20:14] "GET /get_pid HTTP/1.1" 200 -
2019-12-03 22:20:14,351 2637  INFO       getting browser name
2019-12-03 22:20:14,352 2637  INFO       SENDING: {'name': 'get_browser'}
2019-12-03 22:20:14,365 2637  INFO       RECEIVED: b'"firefox"'
2019-12-03 22:20:14,365 2637  INFO       127.0.0.1 - - [03/Dec/2019 22:20:14] "GET /get_browser HTTP/1.1" 200 -
```

This was with version `0.0.3`, which is available via `pypi`/`pip`. Version `0.0.5` produces the expected output.

**Comment by vredesbyyrd** [comment]
Hi, thanks for the info. I updated brotab to `0.5`.  

When running `bt active` brotab times out and crashes. I am not particularly concerned about `bt active` feature anymore, I can live without it.  But figured I should report the errors. 

Perhaps of note, my distribution is on python 3.8. 

```
~ » tail -f '/tmp/brotab.log'                                                                    
2019-12-06 20:00:21,362 INFO       Logger has been created
2019-12-06 20:00:21,369 INFO       Showing active tabs: Namespace(func=<function show_active_tabs at 0x7f4c64c6e280>)
2019-12-06 20:00:21,369 INFO       GET http://localhost:4625/get_pid
2019-12-06 20:00:21,375 INFO       GET http://localhost:4625/get_browser
2019-12-06 20:00:21,383 INFO       Created clients: [<brotab.api.SingleMediatorAPI object at 0x7f4c64c7ccd0>]
2019-12-06 20:00:21,384 INFO       GET http://localhost:4625/get_active_tabs
```
```
~ » bt active                                                                                
Traceback (most recent call last):
  File "/home/clu/.local/bin/bt", line 12, in <module>
    sys.exit(main())
  File "/home/clu/.local/lib/python3.8/site-packages/brotab/main.py", line 536, in main
    exit(run_commands(sys.argv[1:]))
  File "/home/clu/.local/lib/python3.8/site-packages/brotab/main.py", line 529, in run_commands
    result = args.func(args)
  File "/home/clu/.local/lib/python3.8/site-packages/brotab/main.py", line 160, in show_active_tabs
    tabs = api.get_active_tabs(args)
  File "/home/clu/.local/lib/python3.8/site-packages/brotab/api.py", line 101, in get_active_tabs
    return [self.prefix_tab(tab) for tab in self._get('/get_active_tabs').split(',')]
  File "/home/clu/.local/lib/python3.8/site-packages/brotab/api.py", line 201, in _get
    with urlopen(request, timeout=HTTP_TIMEOUT) as response:
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.8/urllib/request.py", line 1321, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1322, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
```
`brotab_mediator.log` was empty. Switching tabs with `bt activate` works fine.

**Comment by vredesbyyrd** [comment]
Hi, thanks for the info. I updated brotab to `0.5`.  

When running `bt active` brotab times out and crashes. I am not particularly concerned about `bt active` feature anymore, I can live without it.  But figured I should report the errors. 

Perhaps of note, my distribution is on python 3.8. 

```
~ » tail -f '/tmp/brotab.log'                                                                    
2019-12-06 20:00:21,362 INFO       Logger has been created
2019-12-06 20:00:21,369 INFO       Showing active tabs: Namespace(func=<function show_active_tabs at 0x7f4c64c6e280>)
2019-12-06 20:00:21,369 INFO       GET http://localhost:4625/get_pid
2019-12-06 20:00:21,375 INFO       GET http://localhost:4625/get_browser
2019-12-06 20:00:21,383 INFO       Created clients: [<brotab.api.SingleMediatorAPI object at 0x7f4c64c7ccd0>]
2019-12-06 20:00:21,384 INFO       GET http://localhost:4625/get_active_tabs
```
```
~ » bt active                                                                                
Traceback (most recent call last):
  File "/home/clu/.local/bin/bt", line 12, in <module>
    sys.exit(main())
  File "/home/clu/.local/lib/python3.8/site-packages/brotab/main.py", line 536, in main
    exit(run_commands(sys.argv[1:]))
  File "/home/clu/.local/lib/python3.8/site-packages/brotab/main.py", line 529, in run_commands
    result = args.func(args)
  File "/home/clu/.local/lib/python3.8/site-packages/brotab/main.py", line 160, in show_active_tabs
    tabs = api.get_active_tabs(args)
  File "/home/clu/.local/lib/python3.8/site-packages/brotab/api.py", line 101, in get_active_tabs
    return [self.prefix_tab(tab) for tab in self._get('/get_active_tabs').split(',')]
  File "/home/clu/.local/lib/python3.8/site-packages/brotab/api.py", line 201, in _get
    with urlopen(request, timeout=HTTP_TIMEOUT) as response:
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.8/urllib/request.py", line 1321, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1322, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
```
`brotab_mediator.log` was empty. Switching tabs with `bt activate` works fine.  

```
~ » tail -f '/tmp/brotab.log'                                                                
2019-12-06 20:15:06,343 INFO       Logger has been created
2019-12-06 20:15:06,349 INFO       Listing tabs
2019-12-06 20:15:06,349 INFO       GET http://localhost:4625/get_pid
2019-12-06 20:15:06,355 INFO       GET http://localhost:4625/get_browser
2019-12-06 20:15:06,365 INFO       Created clients: [<brotab.api.SingleMediatorAPI object at 0x7f6f581ddeb0>]
2019-12-06 20:15:06,366 DEBUG      Using selector: EpollSelector
2019-12-06 20:15:06,366 INFO       GET http://localhost:4625/list_tabs
2019-12-06 20:15:10,068 INFO       Logger has been created
2019-12-06 20:15:10,075 INFO       Activating tab: ['a.1.2']
2019-12-06 20:15:10,075 INFO       GET http://localhost:4625/get_pid
2019-12-06 20:15:10,080 INFO       GET http://localhost:4625/get_browser
2019-12-06 20:15:10,086 INFO       Created clients: [<brotab.api.SingleMediatorAPI object at 0x7f839919bee0>]
2019-12-06 20:15:10,086 INFO       GET http://localhost:4625/activate_tab/2
```

**Comment by balta2ar** [comment]
@vredesbyyrd You may want to try again with versions 1.0.6 (python package version jumped to match the version of the browser extension). Chrome extension is pending review, but Firefox is already 1.0.6 (and of course you can always install locally in developer mode).

**Comment by vredesbyyrd** [comment]
Tested `bt active` on version 1.0.6 and everything works without error now. Closing. 

Thanks for your time!
